---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: {{APP_NAME}}
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/{{GITHUB_ORG}}/{{APP_NAME}}
  ref:
    branch: main
  secretRef:
    name: github-credentials